birthday1 = input ("What is 1st friends birthday?")
print("1st friends birthday is", birthday1)
birthday2 = input ("Whaat is 2nd friend's birthday?")
print("2nd friends birthday is", birthday2)
birthday3 = input ("What is 3rd friend's birtday?")
print("3rd friends birthday is", birthday3)
birthday4 = input ("What is 4th friend's birthday?")
print("4th friends birthday is", birthday4)
birthday5 = input ("What is 5th friend's birthday?")
print("5th friends birthday is", birthday5)